# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71e3c3fee1338941423de22041b2c499504deaacebaa58a32e78d15cf72f1bc255c4c60abfe2b6e1fbbebc8f45f561a6a26883b7fc868e9f40c8c46b80ed85f9

test:
  secret_key_base: 86f7bac369f47b33b62f43cde0b0ec197bd1d95eef3e033ae55df8bc4b0c2f5dde9038db21c5ba414c0ee395d0d853bbd2620c7f951d165f8809190e0a8e2bf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
